spring.application.name=follow-service
server.port=8085

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=${EUREKA_SERVER:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}

logging.level.com.connectsphere.follow_service=INFO
logging.level.org.springframework.web=INFO
logging.file.name=logs/follow-service.log

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
